repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
  - repo: https://github.com/google/yapf
    rev: v0.43.0
    hooks:
      - id: yapf
  - repo: https://github.com/doublify/pre-commit-clang-format.git
    rev: 62302476d0da01515660132d76902359bed0f782
    hooks:
      - id: clang-format
